[package]
name = "cranial-coitus"
authors = ["Chase Wilson <me@chasewilson.dev>"]
version = "0.1.0"
license = "MIT OR Apache-2.0"
edition = "2021"
resolver = "2"

[dependencies]
atty = "0.2.14"
pretty = "0.10.0"
similar = "2.1.0"
clap = "3.0.0-beta.4"
tracing-subscriber = "0.2.25"
tinyvec = { version = "1.5.0", features = ["alloc"] }
tracing = { version = "0.1.29", features = ["release_max_level_info"] }

[profile.release]
debug = 2

    [profile.release.package."*"]
    debug = 2
